version: "2"
argument-count:
    config:
      threshold: 7
plugins:
  bandit:
    enabled: true
  radon:
    enabled: true
  sonarpython:
    enabled: true
exclude_patterns:
  - ".circleci/"
  - ".gitignore"
  - ".pylintrc"
  - ".python-version"
  - "LICENSE"
  - "Pipfile"
  - "Pipfile.lock"
  - "README.md"